// flow-typed signature: 49271a67d5122254f769bc54163bb7e0
// flow-typed version: <<STUB>>/line-reader_vgithub:jedwards1211/line-reader#sync-line-reader/flow_v0.143.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'line-reader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'line-reader' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'line-reader/lib/line_reader' {
  declare module.exports: any
}

declare module 'line-reader/test/line_reader' {
  declare module.exports: any
}

// Filename aliases
declare module 'line-reader/lib/line_reader.js' {
  declare module.exports: $Exports<'line-reader/lib/line_reader'>
}
declare module 'line-reader/test/line_reader.js' {
  declare module.exports: $Exports<'line-reader/test/line_reader'>
}
