// flow-typed signature: ae9e16134a55766124f65eec9ea3d65c
// flow-typed version: <<STUB>>/metacave-flow_vgithub:jedwards1211/metacave-flow/flow_v0.143.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'metacave-flow'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'metacave-flow' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'metacave-flow/index' {
  declare module.exports: $Exports<'metacave-flow'>
}
declare module 'metacave-flow/index.js' {
  declare module.exports: $Exports<'metacave-flow'>
}
