// flow-typed signature: 3a4749ba2a716a5a3fd44e638a03ec3e
// flow-typed version: <<STUB>>/node-getopt_v^0.2.3/flow_v0.143.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-getopt'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-getopt' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-getopt/examples/help' {
  declare module.exports: any
}

declare module 'node-getopt/examples/onedragon' {
  declare module.exports: any
}

declare module 'node-getopt/examples/oneline' {
  declare module.exports: any
}

declare module 'node-getopt/examples/simple' {
  declare module.exports: any
}

declare module 'node-getopt/lib/getopt' {
  declare module.exports: any
}

declare module 'node-getopt/test/test' {
  declare module.exports: any
}

// Filename aliases
declare module 'node-getopt/examples/help.js' {
  declare module.exports: $Exports<'node-getopt/examples/help'>
}
declare module 'node-getopt/examples/onedragon.js' {
  declare module.exports: $Exports<'node-getopt/examples/onedragon'>
}
declare module 'node-getopt/examples/oneline.js' {
  declare module.exports: $Exports<'node-getopt/examples/oneline'>
}
declare module 'node-getopt/examples/simple.js' {
  declare module.exports: $Exports<'node-getopt/examples/simple'>
}
declare module 'node-getopt/index' {
  declare module.exports: $Exports<'node-getopt'>
}
declare module 'node-getopt/index.js' {
  declare module.exports: $Exports<'node-getopt'>
}
declare module 'node-getopt/lib/getopt.js' {
  declare module.exports: $Exports<'node-getopt/lib/getopt'>
}
declare module 'node-getopt/test/test.js' {
  declare module.exports: $Exports<'node-getopt/test/test'>
}
