// flow-typed signature: 66683e1054ee7033793f7b9d20291d9c
// flow-typed version: <<STUB>>/tapable_v^0.2.6/flow_v0.143.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tapable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tapable' {
  declare module.exports: any
  declare export type Tapable = any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tapable/lib/Tapable' {
  declare module.exports: any
}

// Filename aliases
declare module 'tapable/lib/Tapable.js' {
  declare module.exports: $Exports<'tapable/lib/Tapable'>
}
